// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: api/api_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送私聊消息
// 终结点：/send_private_msg
type SendPrivateMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // 对方 QQ 号
	GroupId    int64  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`          // 主动发起临时会话时的来源群号(可选, 机器人本身必须是管理员/群主)
	Message    string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                          // 主要发送的内容
	AutoEscape bool   `protobuf:"varint,4,opt,name=auto_escape,json=autoEscape,proto3" json:"auto_escape,omitempty"` // 消息内容是否作为纯文本发送 ( 即不解析 CQ 码 ) , 只在 message 字段是字符串时有效
}

func (x *SendPrivateMsg) Reset() {
	*x = SendPrivateMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendPrivateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMsg) ProtoMessage() {}

func (x *SendPrivateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMsg.ProtoReflect.Descriptor instead.
func (*SendPrivateMsg) Descriptor() ([]byte, []int) {
	return file_api_api_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendPrivateMsg) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SendPrivateMsg) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendPrivateMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendPrivateMsg) GetAutoEscape() bool {
	if x != nil {
		return x.AutoEscape
	}
	return false
}

// 发送群聊消息
// 终结点：/send_group_msg
type SendGroupMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId    int64  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`          // 群号
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // 要发送的内容
	AutoEscape bool   `protobuf:"varint,3,opt,name=auto_escape,json=autoEscape,proto3" json:"auto_escape,omitempty"` // 消息内容是否作为纯文本发送 ( 即不解析 CQ 码 ) , 只在 message 字段是字符串时有效
}

func (x *SendGroupMsg) Reset() {
	*x = SendGroupMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_api_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendGroupMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMsg) ProtoMessage() {}

func (x *SendGroupMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMsg.ProtoReflect.Descriptor instead.
func (*SendGroupMsg) Descriptor() ([]byte, []int) {
	return file_api_api_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendGroupMsg) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendGroupMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendGroupMsg) GetAutoEscape() bool {
	if x != nil {
		return x.AutoEscape
	}
	return false
}

var File_api_api_message_proto protoreflect.FileDescriptor

var file_api_api_message_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x7f, 0x0a, 0x0e, 0x53,
	0x65, 0x6e, 0x64, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x75, 0x74, 0x6f, 0x5f, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x45, 0x73, 0x63, 0x61, 0x70, 0x65, 0x22, 0x64, 0x0a, 0x0c,
	0x53, 0x65, 0x6e, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x5f, 0x65, 0x73, 0x63, 0x61, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x6f, 0x45, 0x73, 0x63, 0x61,
	0x70, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_api_message_proto_rawDescOnce sync.Once
	file_api_api_message_proto_rawDescData = file_api_api_message_proto_rawDesc
)

func file_api_api_message_proto_rawDescGZIP() []byte {
	file_api_api_message_proto_rawDescOnce.Do(func() {
		file_api_api_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_api_message_proto_rawDescData)
	})
	return file_api_api_message_proto_rawDescData
}

var file_api_api_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_api_message_proto_goTypes = []interface{}{
	(*SendPrivateMsg)(nil), // 0: pb.SendPrivateMsg
	(*SendGroupMsg)(nil),   // 1: pb.SendGroupMsg
}
var file_api_api_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_api_message_proto_init() }
func file_api_api_message_proto_init() {
	if File_api_api_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_api_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendPrivateMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_api_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendGroupMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_api_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_message_proto_goTypes,
		DependencyIndexes: file_api_api_message_proto_depIdxs,
		MessageInfos:      file_api_api_message_proto_msgTypes,
	}.Build()
	File_api_api_message_proto = out.File
	file_api_api_message_proto_rawDesc = nil
	file_api_api_message_proto_goTypes = nil
	file_api_api_message_proto_depIdxs = nil
}
